CREATE TABLE movie (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	title TEXT NOT NULL,
	studios TEXT NOT NULL,
	producers TEXT NOT NULL,
	movie_year TEXT NOT NULL,
	winner BOOLEAN NOT NULL DEFAULT FALSE
);